### ISSUE TITLE
Always-present scrollbar on window (windows 10/firefox)

### ISSUE THREAD

**Issue by nsylv** [aluo-x/813_site#27]
![sidebaralwaysandforever](https://user-images.githubusercontent.com/8961613/39666105-36f0500a-506c-11e8-8b2b-32435ad73fb9.png)

**Comment by ramimanna** [comment]
i think i fixed this? can you check again? thanks! :D

**Comment by nsylv** [comment]
I still see it as of commit 8abe6d410b7cccd402a6c0939adc716408088a7c (initial fixes for responsiveness)

**Comment by ramimanna** [comment]
ooh interesting

**Comment by ramimanna** [comment]
note to ourselves: if all else fails:

```
html {
  overflow: hidden !important;
}
```

**Comment by nsylv** [comment]
gone using ^^
